# (autogenerated content from swagger API)


#' List the available permissions
#'
#'
#'  ### Description
#'  List all the available permissions which can be used to create custom roles.
#'
#'  ### Response Structure
#'  A list of available permissions
#'   - `name`: Name of the permission
#'
#'
#' @param UBIOPS_TOKEN default NULL will search for token in environment
#' @return descriptionhere
#' @export
uo_get_permissions_list <- function(UBIOPS_TOKEN=NULL){
    endpoint=glue::glue("{base}/permissions")
        tk <- check_ubiobstoken(UBIOPS_TOKEN)
        h  <- create_headers(tk)
    body<-'somethinghere'
    res <- httr::GET(url=endpoint,body=body,encode = "json",h)
    httr::stop_for_status(res)
    httr::content(res)
}
